### ISSUE TITLE
i tried to run the pytorch code but having some errors, as i downloaded everything you mentioned but still.

### ISSUE THREAD

**Issue by ejokhan** [wang-h/bert-relation-classification#3]
10/30/2019 19:20:06 - INFO - __main__ -   using L2 regularization with lambda  0.00500
10/30/2019 19:20:08 - INFO - pytorch_transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\Users\EJO\.cache\torch\pytorch_transformers\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
10/30/2019 19:20:11 - INFO - pytorch_transformers.modeling_utils -   loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-pytorch_model.bin from cache at C:\Users\EJO\.cache\torch\pytorch_transformers\54da47087cc86ce75324e4dc9bbb5f66c6e83a7c6bd23baea8b489acc8d09aa4.4d5343a4b979c4beeaadef17a0453d1bb183dd9b084f58b84c7cc781df343ae6
Traceback (most recent call last):
  File "bert.py", line 427, in <module>
    main()
  File "bert.py", line 357, in main
    config.pretrained_model_name, config=bertconfig)
  File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\pytorch_transformers\modeling_utils.py", line 536, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\EJO\bert-relation-classification\model.py", line 66, in __init__
    self.apply(self.init_weights)
  File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 242, in apply
    module.apply(fn)
  File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 242, in apply
    module.apply(fn)
  File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 242, in apply
    module.apply(fn)
  File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 243, in apply
    fn(self)
TypeError: init_weights() takes 1 positional argument but 2 were given

(venv) C:\Users\EJO\bert-relation-classification>

**Comment by wang-h** [comment]
try pytorch_transformers=1.1

**Comment by ejokhan** [comment]
Sir, Can i get the tensorflow based code, as i changed the transformer version but still there is some error


0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/04/2019 15:27:28 - INFO - utils -   label: 15 (id = 15)
11/04/2019 15:27:30 - INFO - __main__ -   ***** Running training *****
11/04/2019 15:27:30 - INFO - __main__ -     Num examples = 8000
11/04/2019 15:27:30 - INFO - __main__ -     Num Epochs = 5
11/04/2019 15:27:30 - INFO - __main__ -     Instantaneous batch size per GPU = 16
11/04/2019 15:27:30 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 16
11/04/2019 15:27:30 - INFO - __main__ -     Gradient Accumulation steps = 1
11/04/2019 15:27:30 - INFO - __main__ -     Total optimization steps = 2500
Epoch:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):                                                              | 0/500 [00:00<?, ?it/s]
  File "bert.py", line 427, in <module>
    main()
  File "bert.py", line 372, in main
    global_step, tr_loss = train(config, train_dataset, model, tokenizer)
  File "bert.py", line 125, in train
    outputs = model(**inputs)
  File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\EJO\bert-relation-classification\model.py", line 96, in forward
    device = logits.get_device()
 RuntimeError: get_device is not implemented for tensors with CPU backend**
Epoch:   0%|                                                                                     | 0/5 [01:17<?, ?it/s]
Iteration:   0%|                                                                               | 0/500 [01:17<?, ?it/s]

(venv) C:\Users\EJO\bert-relation-classification>

**Comment by ejokhan** [comment]
engr.ijaz@outlook.com

Sir this is my email id. thanks a lot for your assistance.

**Comment by wang-h** [comment]
> Sir, Can i get the tensorflow based code, as i changed the transformer version but still there is some error
> 
> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
> 11/04/2019 15:27:28 - INFO - utils - label: 15 (id = 15)
> 11/04/2019 15:27:30 - INFO - **main** - ***** Running training *****
> 11/04/2019 15:27:30 - INFO - **main** - Num examples = 8000
> 11/04/2019 15:27:30 - INFO - **main** - Num Epochs = 5
> 11/04/2019 15:27:30 - INFO - **main** - Instantaneous batch size per GPU = 16
> 11/04/2019 15:27:30 - INFO - **main** - Total train batch size (w. parallel, distributed & accumulation) = 16
> 11/04/2019 15:27:30 - INFO - **main** - Gradient Accumulation steps = 1
> 11/04/2019 15:27:30 - INFO - **main** - Total optimization steps = 2500
> Epoch: 0%| | 0/5 [00:00<?, ?it/s]Traceback (most recent call last): | 0/500 [00:00<?, ?it/s]
> File "bert.py", line 427, in
> main()
> File "bert.py", line 372, in main
> global_step, tr_loss = train(config, train_dataset, model, tokenizer)
> File "bert.py", line 125, in train
> outputs = model(**inputs)
> File "C:\Users\EJO\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs) File "C:\Users\EJO\bert-relation-classification\model.py", line 96, in forward device = logits.get_device() RuntimeError: get_device is not implemented for tensors with CPU backend**
> Epoch: 0%| | 0/5 [01:17<?, ?it/s]
> Iteration: 0%| | 0/500 [01:17<?, ?it/s]
> 
> (venv) C:\Users\EJO\bert-relation-classification>

I think you are using a **CPU-version pytorch.**
If I am right, please delete this "if" section.

**Comment by ejokhan** [comment]
i deleted but it is not working.. is there any other version or GPU-version which i can change and it start working?

**Comment by ejokhan** [comment]
![image](https://user-images.githubusercontent.com/19641451/69030001-4c5b6000-0a11-11ea-9af0-3971f1300a50.png)
![image](https://user-images.githubusercontent.com/19641451/69030060-70b73c80-0a11-11ea-9b15-4ca5d350e993.png)

**Comment by ejokhan** [comment]
even i changed the code as per your guidance, i deleted the if section but still, it is giving the same error

![image](https://user-images.githubusercontent.com/19641451/69030115-9e9c8100-0a11-11ea-9aab-524750daa210.png)
![image](https://user-images.githubusercontent.com/19641451/69030142-acea9d00-0a11-11ea-90f7-7fa211bf09de.png)
